# Generated by Django 5.2.7 on 2025-10-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='substitles_language',
            new_name='subtitles_language',
        ),
    ]
